//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class EditorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EditorSettings defaultInstance = ((EditorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EditorSettings())));
        
        public static EditorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Draw_AllExtents {
            get {
                return ((bool)(this["Draw_AllExtents"]));
            }
            set {
                this["Draw_AllExtents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_AllText {
            get {
                return ((bool)(this["Draw_AllText"]));
            }
            set {
                this["Draw_AllText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_ComplexPreview {
            get {
                return ((bool)(this["Draw_ComplexPreview"]));
            }
            set {
                this["Draw_ComplexPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Draw_Extents {
            get {
                return ((bool)(this["Draw_Extents"]));
            }
            set {
                this["Draw_Extents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Draw_Extents_3D {
            get {
                return ((bool)(this["Draw_Extents_3D"]));
            }
            set {
                this["Draw_Extents_3D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_FloorTiles {
            get {
                return ((bool)(this["Draw_FloorTiles"]));
            }
            set {
                this["Draw_FloorTiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_Grid {
            get {
                return ((bool)(this["Draw_Grid"]));
            }
            set {
                this["Draw_Grid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_ObjCustomLabels {
            get {
                return ((bool)(this["Draw_ObjCustomLabels"]));
            }
            set {
                this["Draw_ObjCustomLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_ObjectFacing {
            get {
                return ((bool)(this["Draw_ObjectFacing"]));
            }
            set {
                this["Draw_ObjectFacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_Objects {
            get {
                return ((bool)(this["Draw_Objects"]));
            }
            set {
                this["Draw_Objects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_ObjTeams {
            get {
                return ((bool)(this["Draw_ObjTeams"]));
            }
            set {
                this["Draw_ObjTeams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Draw_ObjThingNames {
            get {
                return ((bool)(this["Draw_ObjThingNames"]));
            }
            set {
                this["Draw_ObjThingNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_Polygons {
            get {
                return ((bool)(this["Draw_Polygons"]));
            }
            set {
                this["Draw_Polygons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_PreviewTexEdges {
            get {
                return ((bool)(this["Draw_PreviewTexEdges"]));
            }
            set {
                this["Draw_PreviewTexEdges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_Walls {
            get {
                return ((bool)(this["Draw_Walls"]));
            }
            set {
                this["Draw_Walls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_Waypoints {
            get {
                return ((bool)(this["Draw_Waypoints"]));
            }
            set {
                this["Draw_Waypoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Edit_AllowOverride {
            get {
                return ((bool)(this["Edit_AllowOverride"]));
            }
            set {
                this["Edit_AllowOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Edit_PreviewMode {
            get {
                return ((bool)(this["Edit_PreviewMode"]));
            }
            set {
                this["Edit_PreviewMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Edit_SnapGrid {
            get {
                return ((bool)(this["Edit_SnapGrid"]));
            }
            set {
                this["Edit_SnapGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Edit_SnapHalfGrid {
            get {
                return ((bool)(this["Edit_SnapHalfGrid"]));
            }
            set {
                this["Edit_SnapHalfGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Edit_SnapCustom {
            get {
                return ((bool)(this["Edit_SnapCustom"]));
            }
            set {
                this["Edit_SnapCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Save_EnableScripts {
            get {
                return ((bool)(this["Save_EnableScripts"]));
            }
            set {
                this["Save_EnableScripts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Save_ExportNXZ {
            get {
                return ((bool)(this["Save_ExportNXZ"]));
            }
            set {
                this["Save_ExportNXZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Save_ProtectMap {
            get {
                return ((bool)(this["Save_ProtectMap"]));
            }
            set {
                this["Save_ProtectMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DejaVu Sans, 9.75pt")]
        public global::System.Drawing.Font Script_CodeFont {
            get {
                return ((global::System.Drawing.Font)(this["Script_CodeFont"]));
            }
            set {
                this["Script_CodeFont"] = value;
            }
        }
    }
}
